fix: "dcl build" should always show the output of the build
decentraland/cli pull request #524
Opened 2020-10-08 22:05 UTC by menduz

# What? 
Should always show the output of the build. I had a scene not working and it was because it had errors in the code I was not seeing.

# Why? 
Avoid headaches

2020-10-08 22:47 UTC, nchamo approved these changes
Great work!

2020-10-09 09:05 UTC, sandrade-dcl requested changes

2020-10-09 09:05 UTC, sandrade-dcl commented on src/commands/build.ts
> +    await buildTypescript(workDir, false /* silent=false build should always inform errors */, !!args['--watch'])
Only to try to follow a standard in the team about write comments in the code: Wouldn't be cleaner to put these kind of comments out of the function signature? What do you think?

2020-10-09 13:55 UTC, menduz commented on src/commands/build.ts
> +    await buildTypescript(workDir, false /* silent=false build should always inform errors */, !!args['--watch'])
I tend to put what a boolean value is right next to it. Otherwise unless you are reading code in a typescript capable editor you won't know what a wild "false" is in the code.

2020-10-09 14:08 UTC, sandrade-dcl commented on src/commands/build.ts
> +    await buildTypescript(workDir, false /* silent=false build should always inform errors */, !!args['--watch'])
Can't we put this comment on top of the call to the function? or even inside the `buildTypescript()` function as header of it?

For example in C# we write documentation for functions in this way:

`/// <summary>`
`///  Description for the function...`
`/// </summary>`
`/// <param name="payload">Description for param...</param>`

But I don't know what would be the correct way for typescript code.

2020-10-09 14:10 UTC, sandrade-dcl commented on src/commands/build.ts
> +    await buildTypescript(workDir, false /* silent=false build should always inform errors */, !!args['--watch'])
Anyway, I understand you have to move forward with it and we can discuss this kind of things in the future ;)

2020-10-09 14:10 UTC, sandrade-dcl approved these changes

2020-10-09 14:46 UTC, BrianAmadori commented on src/commands/build.ts
> +    await buildTypescript(workDir, false /* silent=false build should always inform errors */, !!args['--watch'])
I'do it like this to make the comment a bit more readable:
```
await buildTypescript(
    workDir, 
    false, // silent=false build should always inform errors 
    !!args['--watch'])
```

We can also add the comment to the signature using this format already present in SDK code:
```
  /**
   * Description...
   * @param silent - when setting this to false the build should always inform errors.
   */
```

2020-10-09 16:28 UTC, merged