feat: import setupExport from decentraland-ecs and call it if exists
decentraland/cli pull request #571
Opened 2021-08-05 13:35 UTC by leamendoza97

# What? 
Find a setupExport.js file in the decentraland-ecs package, if it exists, it's called it instead of standard export.

...

# Why? 
In accordance with the new package structure, this allows setting up a custom package export from the ECS. Also, it's maintaining compatibility with the current structure.
...

2021-08-05 15:46 UTC, menduz requested changes

2021-08-05 15:46 UTC, menduz commented on src/commands/export.ts
> +    externalExport(exportDir, sceneJson.display.title, mappings)
To this function I would pass an object instead of ordered arguments, here is the rationale: https://menduz.com/posts/2019.05.07#at-root-level-always-return-objects-never-arrays

It makes the signatures more extensible.

Also, please add `await` to enable async operations

What I am imagining is to passing something like this:

```ts
await externalExport({
  workingDir,
  exportDir,
  // sceneJson, // <-- this can be inferred from $workingDir/scene.json if necessary.
  mappings
})

2021-08-05 15:46 UTC, menduz commented on src/commands/export.ts
> +    ])
This could be extracted to a function

2021-08-09 14:51 UTC, leamendoza97 commented on src/commands/export.ts
> +    externalExport(exportDir, sceneJson.display.title, mappings)
I already changed this but sceneJson. We only need to replace the Html's title. The sceneJson is loaded in the CLI with dedicated helpers for it (not big deal, json reader, types and something else), and that is the reason why I included it.

2021-08-09 14:52 UTC, leamendoza97 commented on src/commands/export.ts
> +    ])
Done

2021-08-09 16:03 UTC, menduz approved these changes

2021-08-10 12:21 UTC, merged