feat: add payload to update message sceneType and sceneId
decentraland/cli pull request #600
Opened 2021-11-18 19:54 UTC by leanmendoza

# What? 

...

# Why? 

...

2021-11-19 13:59 UTC, menduz requested changes

2021-11-19 13:59 UTC, menduz commented on src/lib/Preview.ts
> +      } catch (err) {}
Always log errors, it will help us debug when we receive support tickets and will help users of the tool understand and fix the issues by themselves
```suggestion
      } catch (err) {
        console.error(err)
      }
```

2021-11-22 12:38 UTC, leanmendoza commented on src/lib/Preview.ts
> +      } catch (err) {}
Thanks, I forgot it

2021-11-22 14:15 UTC, menduz approved these changes

2021-11-22 14:42 UTC, merged